fix(CI build Dockerfile 4)

diff --git a/.github/workflows/.ci.yaml b/.github/workflows/.ci.yaml
--- a/.github/workflows/.ci.yaml
+++ b/.github/workflows/.ci.yaml
@@ -11,11 +11,17 @@ jobs:
     name: Build Docker Image
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
-    - name: Build Docker image
-      run: |
-        docker build -t ansible-role-test:latest -f docker/Dockerfile .
-    - name: Run Docker container
-      run: |
-        docker run --rm ansible-role-test:latest || { echo "Container failed to run"; exit 1; }
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Build Docker image
+        run: |
+          docker build -t ansible-role-test:latest -f docker/Dockerfile .
+
+  run:
+    name: Run Docker Container
+    runs-on: ubuntu-latest
+    needs: build  # Зависимость от job'а сборки
+    steps:
+      - name: Run Docker container
+        run: |
+          docker run --rm ansible-role-test:latest || { echo "Container failed to run"; exit 1; }
diff --git a/123 b/123
--- a/123
+++ b/123
@@ -14,3 +14,18 @@
         run: yamllint roles/
       - name: Run ansible-lint
         run: ansible-lint roles/
+
+
+jobs:
+  build:
+    name: Build Docker Image
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v3
+    - name: Build Docker image
+      run: |
+        docker build -t ansible-role-test:latest -f docker/Dockerfile .
+    - name: Run Docker container
+      run: |
+        docker run --rm ansible-role-test:latest || { echo "Container failed to run"; exit 1; }
