fix(CI build Dockerfile 5)

diff --git a/.github/workflows/.ci.yaml b/.github/workflows/.ci.yaml
--- a/.github/workflows/.ci.yaml
+++ b/.github/workflows/.ci.yaml
@@ -37,3 +37,23 @@ jobs:
       - name: Run role in container
         run: |
           docker run -d --name ansible-container ansible-role-test tail -f /dev/null
+
+  log_check:
+    name: Check Logs
+    runs-on: ubuntu-latest
+    steps:
+      - name: Install jq
+        run: sudo apt update && sudo apt install -y jq
+      - name: Run role in container
+        run: |
+          docker run -d --name ansible-container ansible-role-test tail -f /dev/null
+      - name: Wait for log file to be created
+        run: sleep 10
+      - name: Check ansible-ssh-audit.log
+        run: |
+          docker cp ssh-audit-role:/var/log/ansible-ssh-audit.log ./ansible-ssh-audit.log
+          if [ ! -f ./ansible-ssh-audit.log ]; then
+            echo "Log file not found!"
+            exit 1
+          fi
+          jq empty ./ansible-ssh-audit.log
