fix(CI build Dockerfile 4)

diff --git a/.github/workflows/.ci.yaml b/.github/workflows/.ci.yaml
--- a/.github/workflows/.ci.yaml
+++ b/.github/workflows/.ci.yaml
@@ -42,7 +42,9 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - name: Run Container
-        run: docker run --rm ansible-role-test:latest
+        run: |
+          docker run --rm ansible-role-test:latest || { echo "Container failed to run"; exit 1; }
+
 
   log_check:
     name: Check Logs
